(()=>{
const style=document.createElement('style');
style.textContent=`
.game-ball{position:fixed;left:0;top:0;width:40px;height:40px;z-index:9999;pointer-events:none;display:none;will-change:transform}
.game-ball.on{display:block}.game-dot{width:100%;height:100%;border-radius:50%;background:var(--ink);transform:scale(9);transition:transform .38s cubic-bezier(.18,.82,.28,1.12);will-change:transform}.game-ball.dropped .game-dot{transform:scale(1)}
body.game-running{overscroll-behavior:none;touch-action:none}body.game-running a{pointer-events:none}body.game-running .hero-pupil{opacity:0}body.game-running .footer-eye:after{opacity:.16}.hero-pupil.drop-ready{filter:drop-shadow(0 8px 0 rgba(0,0,0,.08))}
.game-hint{position:fixed;left:50%;bottom:20px;translate:-50% 0;z-index:10000;background:var(--paper);border:2px solid var(--ink);border-radius:999px;padding:8px 13px;font:800 10px/1 system-ui,sans-serif;letter-spacing:.06em;white-space:nowrap;pointer-events:none;opacity:0;transition:opacity .2s}.game-hint.show{opacity:1}
`;
document.head.appendChild(style);
const eye=document.getElementById('heroEye'),pupil=document.getElementById('heroPupil');if(!eye||!pupil)return;
let gameRunning=false,gesture=false,startY=0,maxDown=0,dragPointer=null;
const DROP_DISTANCE=28;
function dragStart(e){if(gameRunning)return;gesture=true;dragPointer=e.pointerId;startY=e.clientY;maxDown=0;try{eye.setPointerCapture(e.pointerId)}catch(_){}}
function dragMove(e){if(!gesture||gameRunning||(dragPointer!==null&&e.pointerId!==dragPointer))return;const down=e.clientY-startY;maxDown=Math.max(maxDown,down);if(maxDown>=DROP_DISTANCE)pupil.classList.add('drop-ready')}
function dragEnd(e){if(!gesture||gameRunning||(dragPointer!==null&&e.pointerId!==dragPointer))return;gesture=false;dragPointer=null;try{eye.releasePointerCapture(e.pointerId)}catch(_){}pupil.classList.remove('drop-ready');if(maxDown>=DROP_DISTANCE)startDropGame()}
eye.addEventListener('pointerdown',dragStart,{passive:true});eye.addEventListener('pointermove',dragMove,{passive:true});eye.addEventListener('pointerup',dragEnd);eye.addEventListener('pointercancel',dragEnd);
const ball=document.createElement('div');ball.className='game-ball';ball.setAttribute('aria-hidden','true');ball.innerHTML='<div class="game-dot"></div>';document.body.appendChild(ball);
const hint=document.createElement('div');hint.className='game-hint';hint.textContent='← 指で左右になぞる →';document.body.appendChild(hint);
let ballX=0,ballY=0,ballVX=0,ballVY=0,ballR=20,gameLast=0,obstacles=[],physicsStarted=false,steerActive=false,steerX=0,keySteer=0;
function beginSteer(e){if(!gameRunning)return;steerActive=true;steerX=e.clientX+scrollX;try{e.target.setPointerCapture?.(e.pointerId)}catch(_){}if(e.cancelable)e.preventDefault()}
function moveSteer(e){if(!gameRunning||!steerActive)return;steerX=e.clientX+scrollX;if(e.cancelable)e.preventDefault()}
function endSteer(e){if(!gameRunning)return;steerActive=false;if(e&&e.cancelable)e.preventDefault()}
window.addEventListener('pointerdown',beginSteer,{passive:false});window.addEventListener('pointermove',moveSteer,{passive:false});window.addEventListener('pointerup',endSteer,{passive:false});window.addEventListener('pointercancel',endSteer,{passive:false});
window.addEventListener('keydown',e=>{if(!gameRunning)return;if(e.key==='ArrowLeft')keySteer=-1;if(e.key==='ArrowRight')keySteer=1});window.addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight')keySteer=0});
function collectTextRects(){const selectors=['.flow-copy h2 .line','.flow-lead','.flow-copy > p:not(.flow-lead)','.choose-kicker','.choose h2','.choose-intro','.view-index','.view-note','.go','.bridge','.section-no','.info-head','.info-cell small','.info-cell b','footer'],rects=[];document.querySelectorAll(selectors.join(',')).forEach(el=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(!node.textContent.trim())continue;const range=document.createRange();range.selectNodeContents(node);[...range.getClientRects()].forEach(r=>{if(r.width>=3&&r.height>=3)rects.push({l:r.left+scrollX-2,r:r.right+scrollX+2,t:r.top+scrollY-2,b:r.bottom+scrollY+2})})}});document.querySelectorAll('.card-eye,.drifting-eye,.info-grid').forEach(el=>{const r=el.getBoundingClientRect();rects.push({l:r.left+scrollX,r:r.right+scrollX,t:r.top+scrollY,b:r.bottom+scrollY})});return rects}
function startDropGame(){if(gameRunning)return;gameRunning=true;physicsStarted=false;steerActive=false;keySteer=0;const pr=pupil.getBoundingClientRect(),cx=pr.left+pr.width/2,cy=pr.top+pr.height/2,bw=Math.max(36,Math.min(42,innerWidth*.105));ball.style.width=bw+'px';ball.style.height=bw+'px';ballR=bw/2;ballX=cx+scrollX;ballY=cy+scrollY;ballVX=0;ballVY=80;obstacles=collectTextRects();document.body.classList.add('game-running');ball.classList.add('on');ball.classList.remove('dropped');ball.style.transform=`translate3d(${(cx-ballR).toFixed(1)}px,${(cy-ballR).toFixed(1)}px,0)`;hint.classList.add('show');setTimeout(()=>hint.classList.remove('show'),1800);void ball.offsetWidth;requestAnimationFrame(()=>ball.classList.add('dropped'));setTimeout(()=>{if(!gameRunning)return;physicsStarted=true;gameLast=performance.now();requestAnimationFrame(gameFrame)},170)}
function collideCircleRect(o){const cx=Math.max(o.l,Math.min(ballX,o.r)),cy=Math.max(o.t,Math.min(ballY,o.b));let dx=ballX-cx,dy=ballY-cy,d2=dx*dx+dy*dy;if(d2>=ballR*ballR)return;let nx=0,ny=0,pen=0;if(d2>.0001){const d=Math.sqrt(d2);nx=dx/d;ny=dy/d;pen=ballR-d}else{const dl=Math.abs(ballX-o.l),dr=Math.abs(o.r-ballX),dt=Math.abs(ballY-o.t),db=Math.abs(o.b-ballY),m=Math.min(dl,dr,dt,db);if(m===dl){nx=-1;pen=ballR+dl}else if(m===dr){nx=1;pen=ballR+dr}else if(m===dt){ny=-1;pen=ballR+dt}else{ny=1;pen=ballR+db}}ballX+=nx*(pen+.7);ballY+=ny*(pen+.7);const vn=ballVX*nx+ballVY*ny;if(vn<0){const bounce=.5;ballVX-=(1+bounce)*vn*nx;ballVY-=(1+bounce)*vn*ny;ballVX*=.94}}
function gameFrame(now){if(!gameRunning||!physicsStarted)return;const dt=Math.min(.026,Math.max(.006,(now-gameLast)/1000));gameLast=now;if(steerActive){const dx=steerX-ballX;ballVX+=Math.max(-1500,Math.min(1500,dx*11))*dt}else if(keySteer){ballVX+=keySteer*1450*dt}ballVY+=960*dt;ballVX*=Math.pow(.982,dt*60);ballVY=Math.min(ballVY,720);ballX+=ballVX*dt;ballY+=ballVY*dt;const left=ballR+5,right=Math.min(document.documentElement.clientWidth,720)-ballR-5;if(ballX<left){ballX=left;ballVX=Math.abs(ballVX)*.58}if(ballX>right){ballX=right;ballVX=-Math.abs(ballVX)*.58}for(const o of obstacles){if(o.b<ballY-ballR-80||o.t>ballY+ballR+80)continue;collideCircleRect(o)}const desiredScroll=Math.max(0,Math.min(document.documentElement.scrollHeight-innerHeight,ballY-innerHeight*.58));window.scrollTo(0,scrollY+(desiredScroll-scrollY)*Math.min(1,dt*6.5));ball.style.transform=`translate3d(${(ballX-scrollX-ballR).toFixed(1)}px,${(ballY-scrollY-ballR).toFixed(1)}px,0)`;const goal=document.querySelector('.footer-eye');if(goal){const gr=goal.getBoundingClientRect(),gx=gr.left+gr.width/2+scrollX,gy=gr.top+gr.height/2+scrollY,dx=ballX-gx,dy=ballY-gy;if(dx*dx+dy*dy<52*52||ballY>gy+70){finishGame(gx,gy);return}}requestAnimationFrame(gameFrame)}
function finishGame(gx,gy){gameRunning=false;physicsStarted=false;steerActive=false;keySteer=0;hint.classList.remove('show');const sx=gx-scrollX-ballR,sy=gy-scrollY-ballR;ball.style.transition='transform .34s cubic-bezier(.2,.9,.3,1),opacity .25s ease .2s';ball.style.transform=`translate3d(${sx}px,${sy}px,0)`;setTimeout(()=>{ball.style.opacity='0';document.body.classList.remove('game-running');setTimeout(()=>{ball.classList.remove('on','dropped');ball.style.transition='';ball.style.opacity='1';pupil.style.opacity=''},260)},360)}
})();
